// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ClipService watches the clipboard, keeps the history and answers the interface.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Clear forgets the unpinned texts; the clipboard itself is left alone.
 */
export function Clear(): $CancellablePromise<void> {
    return $Call.ByID(1034691268);
}

/**
 * Copy puts the entry back on the clipboard, and the panel stays open for the next one.
 */
export function Copy(id: string): $CancellablePromise<void> {
    return $Call.ByID(738535650, id);
}

export function DismissError(): $CancellablePromise<void> {
    return $Call.ByID(2148176837);
}

/**
 * Open hands a link to the browser, or an email address to the mail client.
 */
export function Open(id: string): $CancellablePromise<void> {
    return $Call.ByID(2577863271, id);
}

/**
 * QRCode returns the entry as a PNG image, ready for an <img> tag.
 */
export function QRCode(id: string): $CancellablePromise<string> {
    return $Call.ByID(3736011793, id);
}

/**
 * SetPaused is called by the panel and by the tray menu; each follows the other.
 */
export function SetPaused(paused: boolean): $CancellablePromise<void> {
    return $Call.ByID(3495457847, paused);
}

export function SetPinned(id: string, pinned: boolean): $CancellablePromise<void> {
    return $Call.ByID(4132550019, id, pinned);
}

/**
 * SetSecret hides a text (a password) from whoever looks over the shoulder;
 * it is still copied in clear.
 */
export function SetSecret(id: string, secret: boolean): $CancellablePromise<void> {
    return $Call.ByID(3154968077, id, secret);
}

/**
 * State returns everything the interface shows.
 */
export function State(): $CancellablePromise<$models.State> {
    return $Call.ByID(537754876);
}
