// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as history$0 from "./internal/history/models.js";

export interface EntryView {
    "id": string;
    "text": string;
    "truncated": boolean;
    "copiedAt": string | null;
    "pinned": boolean;
    "kind": history$0.Kind;

    /**
     * Secret: the text is not sent to the interface at all, only its mark.
     */
    "secret": boolean;
}

export interface State {
    "entries": EntryView[] | null;
    "paused": boolean;

    /**
     * Current is the id of the entry now on the clipboard, ready for Ctrl+V.
     */
    "current": string;
    "error": string;
}
