// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as history$0 from "./internal/history/models.js";

export interface EntryView {
    "id": string;
    "text": string;
    "truncated": boolean;
    "copiedAt": string | null;
    "pinned": boolean;
    "kind": history$0.Kind;

    /**
     * Secret: nothing of the content is sent to the interface, only its mark.
     */
    "secret": boolean;

    /**
     * Files: the copied paths; Missing counts those no longer found.
     */
    "files": string[] | null;
    "missing": number;
    "folder": boolean;

    /**
     * Place is the folder the files come from, home shortened to ~.
     */
    "place": string;

    /**
     * Thumb is the address of the image's thumbnail; Name, a screenshot's file name.
     */
    "thumb": string;
    "width": number;
    "height": number;
    "capture": boolean;
    "name": string;
}

export interface State {
    "entries": EntryView[] | null;
    "paused": boolean;

    /**
     * Current is the id of the entry now on the clipboard, ready for Ctrl+V.
     */
    "current": string;
    "error": string;

    /**
     * CaptureMode: Print Screen belongs to ClipQR, which saves each screenshot
     * in CapturesDir. CaptureAvailable is false where the key cannot be taken.
     */
    "captureMode": boolean;
    "captureAvailable": boolean;
    "capturesDir": string;
}
