// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Kind tells the interface which icon to show and whether the text can be opened.
 */
export enum Kind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    KindText = "text",
    KindLink = "link",
    KindEmail = "email",
    KindPhone = "phone",
};
